apiVersion: v2
name: tr-system
description: A Helm chart for Kubernetes
type: application
version: 0.0.2
appVersion: 0.0.2
dependencies:
  - name: tr-authentication-api
    version: 1.4.5-e4844ef82c8aaf5397864a8ce9e50839768ccb9b
    repository: http://trend-dev.ru:5000
  - name: tr-trendrealty-api
    version: 5.27.8-fbdd5c816699af6e63882275afbe12e531cf6b2e
    repository: http://trend-dev.ru:5000
