apiVersion: v2
name: tr-system
description: A Helm chart for Kubernetes
type: application
version: 0.0.2
appVersion: 0.0.2
dependencies:
  - name: tr-authentication-api
    version: 2.0.14-278be2ab1e9a327d9349d747b60dc178c738e5a9
    repository: http://trend-dev.ru:5000
  - name: tr-trendrealty-api
    version: 5.29.1-1c19400dfbb79c3af074a3aae6bfc2163ac48e33
    repository: http://trend-dev.ru:5000
  - name: tr-questionnaire-api
    version: 1.3.2-587ecedbc04740cbe0dfbf19a1086d3980bd1601
    repository: http://trend-dev.ru:5000
  - name: ta-cabinets-api
    version: 1.4.2-92f3884b3441e3326586ad2a54e4e0911a9b46cb
    repository: http://trend-dev.ru:5000
  - name: tr-cp-api
    version: 1.10.13-e17b454e29dd0d5a9fda0301983188917adfa485
    repository: http://trend-dev.ru:5000
