apiVersion: v2
name: tr-system
description: A Helm chart for Kubernetes
type: application
version: 0.0.2
appVersion: 0.0.2
dependencies:
  - name: tr-authentication-api
    version: 2.1.3-fbf99785f2492151f60dbc27e0feaa0436ba285c
    repository: oci://docker-registry.trendagent.ru:5000/helm-charts
  - name: tr-trendrealty-api
    version: 5.29.2-a2a1715b547f91a100a799303ac5d29c739e244e
    repository: oci://docker-registry.trendagent.ru:5000/helm-charts
  - name: tr-questionnaire-api
    version: 1.3.6-d72fe51f5fcd7541b8f40cd8b51b511b902f0eb5
    repository: oci://docker-registry.trendagent.ru:5000/helm-charts
  - name: ta-cabinets-api
    version: 1.5.11-acdbeb4a3777324712469a438975976fcdbfb32d
    repository: oci://docker-registry.trendagent.ru:5000/helm-charts
  - name: tr-cp-api
    version: 1.10.14-ce34b2ca923418b169f81bba0888043c6b28062b
    repository: oci://docker-registry.trendagent.ru:5000/helm-charts
