apiVersion: v2
name: tr-system
description: A Helm chart for Kubernetes
type: application
version: 0.0.2
appVersion: 0.0.2
dependencies:
  - name: tr-authentication-api
    version: 2.0.13-4f71053cfadac45c25ff5f8e657c02d04ac93643
    repository: http://trend-dev.ru:5000
  - name: tr-trendrealty-api
    version: 5.29.1-1c19400dfbb79c3af074a3aae6bfc2163ac48e33
    repository: http://trend-dev.ru:5000
  - name: tr-questionnaire-api
    version: 1.3.2-587ecedbc04740cbe0dfbf19a1086d3980bd1601
    repository: http://trend-dev.ru:5000
  - name: ta-cabinets-api
    version: 1.5.2-3b03270b4fc80e5bffb69d7efaa0716731c42f6c
    repository: http://trend-dev.ru:5000
  - name: tr-cp-api
    version: 1.10.13-e17b454e29dd0d5a9fda0301983188917adfa485
    repository: http://trend-dev.ru:5000
