apiVersion: v2
name: tr-system
description: A Helm chart for Kubernetes
type: application
version: 0.0.2
appVersion: 0.0.2
dependencies:
  - name: tr-authentication-api
    version: 2.0.11-67e2b95bf5375dfb983a67de2a5bb319bf73ba5a
    repository: http://trend-dev.ru:5000
  - name: tr-trendrealty-api
    version: 5.29.1-1c19400dfbb79c3af074a3aae6bfc2163ac48e33
    repository: http://trend-dev.ru:5000
  - name: tr-questionnaire-api
    version: 1.2.4-00c9db864293328a084a08f6dace07c1f6b644e2
    repository: http://trend-dev.ru:5000
  - name: ta-cabinets-api
    version: 1.5.0-02809a056271c9f3c09df9109abf061bf25bc8ba
    repository: http://trend-dev.ru:5000
  - name: tr-cp-api
    version: 1.10.13-e17b454e29dd0d5a9fda0301983188917adfa485
    repository: http://trend-dev.ru:5000
