apiVersion: v2
name: tr-system
description: A Helm chart for Kubernetes
type: application
version: 0.0.2
appVersion: 0.0.2
dependencies:
  - name: tr-authentication-api
    version: 2.2.4-92d258788fae2ec93d22531456ad2ca7a1d12151
    repository: oci://docker-registry.trendagent.ru:5000/helm-charts
  - name: tr-trendrealty-api
    version: 5.29.3-003581cdf0f935b38912a5a0f24a64ada8a8bfc7
    repository: oci://docker-registry.trendagent.ru:5000/helm-charts
  - name: tr-questionnaire-api
    version: 1.3.8-f276990dd1db7387b01c0ef5f26d23676d8f8604
    repository: oci://docker-registry.trendagent.ru:5000/helm-charts
  - name: ta-cabinets-api
    version: 1.6.3-56f3de66aa51658060ce0ba5fc499ebb02ea6b7d
    repository: oci://docker-registry.trendagent.ru:5000/helm-charts
  - name: tr-cp-api
    version: 1.10.15-fa5617cd2ce3005ed00e7cfac774750e0b5fa948
    repository: oci://docker-registry.trendagent.ru:5000/helm-charts
