apiVersion: v2
name: tr-system
description: A Helm chart for Kubernetes
type: application
version: 0.0.2
appVersion: 0.0.2
dependencies:
  - name: tr-authentication-api
    version: 2.0.9-3ab0e2cc5187cad1e52095f3b7d4a461ca8833a9
    repository: http://trend-dev.ru:5000
  - name: tr-trendrealty-api
    version: 5.28.0-2fae8bbe019fad2bd129232dc135c1c5d7c305f3
    repository: http://trend-dev.ru:5000
  - name: tr-questionnaire-api
    version: 1.2.3-26648ab9f43381eec13dc8a9d1a57414bea6776b
    repository: http://trend-dev.ru:5000
  - name: tr-cp-api
    version: 1.10.13-e845fd1e904efd2423241ad62f8471c568c76110
    repository: http://trend-dev.ru:5000
