apiVersion: v2
name: tr-system
description: A Helm chart for Kubernetes
type: application
version: 0.0.2
appVersion: 0.0.2
dependencies:
  - name: tr-authentication-api
    version: 2.0.6-6e125932a62631de00dc4c207af0433cf7e0590c
    repository: http://trend-dev.ru:5000
  - name: tr-trendrealty-api
    version: 5.27.11-0d1a432791bea72d80a895bb37d5bf8de6eb3745
    repository: http://trend-dev.ru:5000
