apiVersion: v2
name: tr-system
description: A Helm chart for Kubernetes
type: application
version: 0.0.2
appVersion: 0.0.2
dependencies:
  - name: tr-authentication-api
    version: 2.0.11-67e2b95bf5375dfb983a67de2a5bb319bf73ba5a
    repository: http://trend-dev.ru:5000
  - name: tr-trendrealty-api
    version: 5.28.1-4e1d8e5c08a41b93f75ca8b9c66f3b784386b0ab
    repository: http://trend-dev.ru:5000
  - name: tr-questionnaire-api
    version: 1.2.3-26648ab9f43381eec13dc8a9d1a57414bea6776b
    repository: http://trend-dev.ru:5000
  - name: ta-cabinets-api
    version: 1.3.12-68e8998ec1005d635a80afea7d4e7ec4ff0c5a2f
    repository: http://trend-dev.ru:5000
  - name: tr-cp-api
    version: 1.10.13-e17b454e29dd0d5a9fda0301983188917adfa485
    repository: http://trend-dev.ru:5000
