apiVersion: v2
name: tr-system
description: A Helm chart for Kubernetes
type: application
version: 0.0.2
appVersion: 0.0.2
dependencies:
  - name: tr-authentication-api
    version: 1.4.3-30f98b2d6a792a285eeeb6836cd0eb270de65889
    repository: http://trend-dev.ru:5000
  - name: tr-trendrealty-api
    version: 100.500.0-check
    repository: http://trend-dev.ru:5000
