apiVersion: v2
name: tr-system
description: A Helm chart for Kubernetes
type: application
version: 0.0.2
appVersion: 0.0.2
dependencies:
  - name: tr-authentication-api
    version: 2.0.0-658c91d82c31df50e216a0d3a31327429c420820
    repository: http://trend-dev.ru:5000
  - name: tr-trendrealty-api
    version: 5.27.9-d1a83f511e65fa0e286e2ede9989208bce35cdf8
    repository: http://trend-dev.ru:5000
